version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ypg_attendance
      POSTGRES_USER: ypg_user
      POSTGRES_PASSWORD: ypg_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            gunicorn ypg_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ypg_user:ypg_password@db:5432/ypg_attendance
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume: 