# Generated by Django 5.2.3 on 2025-06-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApologyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('congregation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('meeting_date', models.DateField()),
                ('timestamp', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('congregation', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('local', 'Local'), ('district', 'District')], max_length=10)),
                ('meeting_date', models.DateField()),
                ('timestamp', models.TimeField()),
            ],
        ),
    ]
