# Generated by Django 5.2.3 on 2025-06-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apologyentry',
            name='type',
            field=models.CharField(choices=[('local', 'Local'), ('district', 'District')], default='local', max_length=10),
            preserve_default=False,
        ),
    ]
