# Generated by Django 5.2.3 on 2025-06-21 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_credential_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apologyentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.credential'),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.credential'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
