# Generated by Django 5.2.3 on 2025-06-23 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apologyentry_submitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='apologyentry',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendanceentry',
            name='timestamp',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
