# Generated by Django 5.2.3 on 2025-06-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='login_password',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='login_username',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
