# Generated by Django 5.2.3 on 2025-07-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_meeting_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Username or IP address for tracking', max_length=150)),
                ('attempt_type', models.CharField(choices=[('username_password', 'Username/Password'), ('pin', 'PIN')], max_length=20)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('first_failed_attempt', models.DateTimeField(auto_now_add=True)),
                ('last_failed_attempt', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('identifier', 'attempt_type')},
            },
        ),
    ]
