# Generated by Django 5.2.4 on 2026-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('general', 'General Meeting'), ('council', 'Council Meeting'), ('emergency', 'Emergency Meeting')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='CredentialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('username', 'Username'), ('password', 'Password'), ('pin', 'PIN')], max_length=20)),
                ('credential_value', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['credential_type', 'user_id'], name='core_creden_credent_172604_idx')],
                'unique_together': {('credential_type', 'credential_value', 'user_id')},
            },
        ),
    ]
