# Generated by Django 5.2.4 on 2026-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_meeting_meeting_type_credentialhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='custom_participant_limit',
            field=models.IntegerField(blank=True, help_text='Custom limit per local. If null, uses default: General=5, Council=2, Emergency=unlimited', null=True),
        ),
    ]
