# Generated by Django 5.2.4 on 2026-06-23 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_meeting_custom_participant_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='login_password',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='login_username',
        ),
    ]
