# Generated by Django 5.2.4 on 2026-06-24 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_credential_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='duration_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
