# Generated by Django 5.2.3 on 2026-08-21 08:04

import django.db.models.deletion
from django.db import migrations, models


def dedupe_active_attendance_entries(apps, schema_editor):
    """Soft-delete newer duplicates so the unique constraint can be applied."""
    AttendanceEntry = apps.get_model('core', 'AttendanceEntry')
    seen = set()
    for entry in AttendanceEntry.objects.filter(is_deleted=False).order_by('id'):
        key = (entry.phone, entry.meeting_date, entry.type)
        if key in seen:
            entry.is_deleted = True
            entry.save(update_fields=['is_deleted'])
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_meeting_duration_hours_meeting_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_count', models.IntegerField(default=0)),
                ('apology_count', models.IntegerField(default=0)),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.RunPython(dedupe_active_attendance_entries, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='attendanceentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('phone', 'meeting_date', 'type'), name='unique_active_phone_meeting_type'),
        ),
        migrations.AddField(
            model_name='databackup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.credential'),
        ),
    ]
