# Generated by Django 5.2.4 on 2026-08-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_databackup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='absence_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
