# Generated by Django 5.2.3 on 2026-08-22 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_localcontact_meeting_absence_reminder_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, default='', max_length=150)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('password_change', 'Password Change'), ('password_reset', 'Password Reset')], default='password_change', max_length=30)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='core.credential')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
