import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { MeetingDateProvider } from '@components/MeetingDateContext';
import AutoLogoutWrapper from '../components/AutoLogoutWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script dangerouslySetInnerHTML={{
          __html: `
            // Force HTTP in development
            if (window.location.protocol === 'https:' && window.location.hostname === 'localhost') {
              window.location.href = window.location.href.replace('https:', 'http:');
            }
          `
        }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MeetingDateProvider>
          <AutoLogoutWrapper />
          <Toaster position="top-center" />
          {children}
        </MeetingDateProvider>
      </body>
    </html>
  );
}
